In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf
import cv2
import os
from keras.utils import to_categorical
from keras.optimizers import Adam
from keras.preprocessing.image import ImageDataGenerator
import keras
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay
import matplotlib.pyplot as plt

In [2]:
path = "C:\\Users\\monke\\Downloads\\python cnn\\"
    
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

training_set = train_datagen.flow_from_directory(path + 'train19',
                                                 target_size = (128, 128),
                                                 batch_size = 64,
                                                 class_mode = 'categorical')
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory(path + 'test19',
                                            target_size = (128, 128),
                                            batch_size = 64,
                                            class_mode = 'categorical')

Found 19552 images belonging to 19 classes.
Found 19552 images belonging to 19 classes.


In [3]:

cnn = tf.keras.models.Sequential()
print("Building Neural Network.....")
cnn.add(tf.keras.layers.Conv2D(filters=16, kernel_size=(3,3), padding="same", activation='tanh', input_shape=[128, 128, 3]))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size=2, strides=2,padding="same"))
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(3,3), padding="same", activation='tanh'))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size=2, strides=2, padding="same"))
cnn.add(tf.keras.layers.Conv2D(filters=64, kernel_size=(3,3), padding="same", activation='tanh'))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size=2, strides=2, padding="same"))
cnn.add(tf.keras.layers.Conv2D(filters=128, kernel_size=(3,3), padding="same", activation='tanh'))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size=2, strides=2, padding="same"))
cnn.add(tf.keras.layers.Conv2D(filters=256, kernel_size=(3,3), padding="same", activation='tanh'))
cnn.add(tf.keras.layers.Flatten())
cnn.add(tf.keras.layers.Dense(units=128, activation='tanh'))
cnn.add(tf.keras.layers.Dense(units=9, activation='softmax'))
    
print("Training cnn.....")
cnn.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
print(cnn.summary())

Building Neural Network.....
Training cnn.....
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 128, 128, 16)      448       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 64, 64, 16)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 64, 64, 32)        4640      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 32, 32, 32)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 32, 32, 64)        18496     
                                                                 
 max_pool

In [13]:
model = cnn.fit(training_set, validation_data = test_set, batch_size=70, epochs = 200)

Epoch 1/200
167/167 [==============================] - 238s 1s/step - loss: 1.9153 - accuracy: 0.3073 - val_loss: 1.7402 - val_accuracy: 0.3968
Epoch 2/200
167/167 [==============================] - 142s 847ms/step - loss: 1.5718 - accuracy: 0.4398 - val_loss: 1.4943 - val_accuracy: 0.4746
Epoch 3/200
167/167 [==============================] - 142s 852ms/step - loss: 1.3803 - accuracy: 0.5255 - val_loss: 1.2159 - val_accuracy: 0.5869
Epoch 4/200
167/167 [==============================] - 150s 897ms/step - loss: 1.2180 - accuracy: 0.5843 - val_loss: 1.0919 - val_accuracy: 0.6267
Epoch 5/200
167/167 [==============================] - 156s 935ms/step - loss: 1.1128 - accuracy: 0.6186 - val_loss: 0.9758 - val_accuracy: 0.6651
Epoch 6/200
167/167 [==============================] - 142s 851ms/step - loss: 1.0003 - accuracy: 0.6607 - val_loss: 0.8580 - val_accuracy: 0.7079
Epoch 7/200
167/167 [==============================] - 139s 833ms/step - loss: 0.9136 - accuracy: 0.6920 - val_loss: 0.77

: 

: 

In [7]:
path = 'modelbuild.h5'
cnn.save(path)
print("Weight Created")

Weight Created


In [3]:
model=keras.models.load_model('modelbuild19_30e.h5')

In [4]:
ans=model.predict(test_set)

306/306 [==============================] - 95s 308ms/step


In [5]:
classIndex=np.argmax(ans,axis=1)
print(classIndex)

def getName9(classNo):
    if   classNo == 0: return 'Apple'
    elif classNo == 1: return 'Avocado'
    elif classNo == 2: return 'Banana'
    elif classNo == 3: return 'Cherry'
    elif classNo == 4: return 'Kiwi'
    elif classNo == 5: return 'Orange'
    elif classNo == 6: return 'Pineapple'
    elif classNo == 7: return 'Strawberries'
    elif classNo == 8: return 'Watermelon'
    else: pass
    
def getName19(classNo):
    if   classNo == 0: return 'Apple'
    elif classNo == 1: return 'Avocado'
    elif classNo == 2: return 'Banana'
    elif classNo == 3: return 'Bell Pepper'
    elif classNo == 4: return 'Bitter Gourd'
    elif classNo == 5: return 'Blueberry'
    elif classNo == 6: return 'Cherry'
    elif classNo == 7: return 'Coconut'
    elif classNo == 8: return 'Dragonfruit'
    elif classNo == 9: return 'Durian'
    elif classNo == 10: return 'Eggplant'
    elif classNo == 11: return 'Grape'
    elif classNo == 12: return 'Kiwi'
    elif classNo == 13: return 'Lime'
    elif classNo == 14: return 'Mangosteen'
    elif classNo == 15: return 'Orange'
    elif classNo == 16: return 'Peanut'
    elif classNo == 17: return 'Tomato'
    elif classNo == 18: return 'Watermelon'
    else: pass
print(getName19(classIndex[1]))

[ 4 14 10 ... 16  9  8]
Mangosteen


In [135]:
ans.argmax()

75

In [10]:
y=np.concatenate([test_set.next()[1] for i in range(test_set.__len__())])

In [130]:
y.shape

(19552, 19)

In [8]:
y_pred=np.round(ans)
print(y_pred)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
%matplotlib notebook

labels9 = ['Apple','Avocado','Banana','Cherry','Kiwi','Orange','Pineapple','Strawberries','Watermelon']
labels19 = [
    'Apple',
    'Avocado',
    'Banana',
    'Bell Pepper',
    'Bitter Gourd',
    'Blueberry',
    'Cherry',
    'Coconut',
    'Dragonfruit',
    'Durian',
    'Eggplant',
    'Grape',
    'Kiwi',
    'Lime',
    'Mangosteen',
    'Orange',
    'Peanut',
    'Tomato',
    'Watermelon'
    ]
cm=confusion_matrix(y_true=y.argmax(axis=1),y_pred=y_pred.argmax(axis=1),normalize='true')
disp=ConfusionMatrixDisplay(cm,display_labels=labels19)
fig, ax = plt.subplots(figsize=(16,9))
disp.plot(ax=ax,xticks_rotation=45,cmap=plt.cm.Blues)
plt.savefig('cm19c30e5_temp.png')
plt.show()

<IPython.core.display.Javascript object>

In [17]:
np.diag(cm)

array([0.05901912, 0.05474765, 0.06712565, 0.038     , 0.05106778,
       0.04690619, 0.05084746, 0.04492188, 0.04830918, 0.06822612,
       0.04940711, 0.04453049, 0.05841584, 0.03861386, 0.05067873,
       0.04263094, 0.0462963 , 0.049     , 0.05220884])

In [24]:
print(training_set.class_indices)

{'apple': 0, 'avocado': 1, 'banana': 2, 'bell pepper': 3, 'bitter gourd': 4, 'blueberry': 5, 'cherry': 6, 'coconut': 7, 'dragonfruit': 8, 'durian': 9, 'eggplant': 10, 'grape': 11, 'kiwi': 12, 'lime': 13, 'mangosteen': 14, 'orange': 15, 'peanut': 16, 'tomato': 17, 'watermelon': 18}
